"""Draws the Instant Launcher icon from the 3D model in il_model.py, so the
SVG, the Blender scene and the mark the window draws cannot drift apart.

Projection: 2:1 dimetric, the pixel-art isometric. A ground unit along X
maps to (1, 0.5), along Y to (1, -0.5); a vertical unit maps to
(0, -1.2247), which a real cube needs: its side height is 0.612 of its
rhombus width, not 0.5. Faces are lit like the Blender scene: three
shadowless suns (above 3.0, front 2.2, right 1.3) plus the dark world.

    python3 iso_svg.py --svg ../instant-launcher.svg \
        --plain ../instant-launcher-plain.svg --go ../../internal/gui/mark_faces.go

The icon is the mark alone on a transparent square, for the desktop: dock and
application grid, where the shelf behind it is the desktop's to draw. The
plain one is the same mark cropped to its own edges, for the README. The Go
file is the faces as a table for mark() in internal/gui/draw.go, which draws
its own rounded tile behind them — inside the window the mark sits in a
panel, not on a shelf of icons.
"""
import argparse
import math

from il_model import BASE, build, normal

VERT = math.cos(math.radians(30)) * math.sqrt(2)   # 1.2247
VIEW = (1, -1, 1)
SUNS = ((0, 0, 1, 3.0), (0, -1, 0, 2.2), (1, 0, 0, 1.3))
AMBIENT = "#1E2128"
TILE, MARK = 512, 372   # the canvas edge and the mark's height within it

# How much of its box an icon fills in a dock. The ones it stands next to —
# Discord, Cider — ship roughly a sixth of theirs as padding, and drawn edge
# to edge ours read as oversized beside them: measured in the dock, 48 px
# wide where both neighbours were 40. The mark is sized to the same share, so
# it takes up the room its neighbours do.
DOCK_FILL = 40 / 48
ICON_MARK = TILE * DOCK_FILL


def to_linear(v):
    v /= 255
    return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4


def to_srgb(v):
    v = max(0.0, min(1.0, v))
    v = v * 12.92 if v <= 0.0031308 else 1.055 * v ** (1 / 2.4) - 0.055
    return round(v * 255)


def hexlin(h):
    return [to_linear(int(h[i:i + 2], 16)) for i in (1, 3, 5)]


def shade(mat, n):
    light = sum(e * max(0.0, n[0] * lx + n[1] * ly + n[2] * lz) for lx, ly, lz, e in SUNS) / SUNS[0][3]
    col = [to_srgb(b * light + a * 1.1) for b, a in zip(hexlin(BASE[mat]), hexlin(AMBIENT))]
    return "#%02X%02X%02X" % tuple(col)


def proj(p):
    x, y, z = p
    return (x + y, 0.5 * (x - y) - VERT * z)


def visible(face):
    n = normal(face)
    return n[0] * VIEW[0] + n[1] * VIEW[1] + n[2] * VIEW[2] > 1e-9


def faces(slab, gap, mark=MARK):
    """The visible faces in drawing order, as (colour, [(x, y), ...]) in
    the tile's 512-unit square. The order is the model's part order (stack
    bottom to top, then the letters, which stand in front of everything);
    within a prism the side faces first and the main face last, since it
    is the nearest plane."""
    draw = []
    for name, mat, main, sides, back in build(slab, gap):
        for face in sides + [back, main]:
            if visible(face):
                draw.append((shade(mat, normal(face)), [proj(p) for p in face]))
    xs = [x for _, pts in draw for x, _ in pts]
    ys = [y for _, pts in draw for _, y in pts]
    k = min(mark / (max(ys) - min(ys)), mark / (max(xs) - min(xs)))
    ox = TILE / 2 - (min(xs) + max(xs)) / 2 * k
    oy = TILE / 2 - (min(ys) + max(ys)) / 2 * k
    return [(col, [(x * k + ox, y * k + oy) for x, y in pts]) for col, pts in draw]


def svg(draw, slab, gap, plain):
    fmt = lambda pts: " ".join(f"{x:.1f} {y:.1f}" for x, y in pts)
    if plain:
        xs = [x for _, pts in draw for x, _ in pts]
        ys = [y for _, pts in draw for _, y in pts]
        pad = 4
        x0, y0 = math.floor(min(xs)) - pad, math.floor(min(ys)) - pad
        w, h = math.ceil(max(xs)) + pad - x0, math.ceil(max(ys)) + pad - y0
        box = f"{x0} {y0} {w} {h}"
        size = f'width="{w}" height="{h}"'
    else:
        box, size = f"0 0 {TILE} {TILE}", f'width="{TILE}" height="{TILE}"'
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}" {size} role="img" aria-labelledby="title desc">',
           '  <title id="title">Instant Launcher</title>',
           '  <desc id="desc">A grass block cut into three stacked instance slabs, earth brown with a skin of grass on top.</desc>',
           f'  <!-- Generated by packaging/mark/iso_svg.py from il_model.py (slab {slab:g}, gap {gap:g}); edit the model, not this file. -->']
    for col, pts in draw:
        out.append(f'  <path d="M{fmt(pts)}Z" fill="{col}"/>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


def go(draw):
    out = ["// Code generated by packaging/mark/iso_svg.py; DO NOT EDIT.",
           "",
           "package gui",
           "",
           'import "gioui.org/f32"',
           "",
           "// markFaces are the visible faces of the icon's model, projected into the",
           "// 512-unit tile and lit like packaging/instant-launcher.svg, in drawing",
           "// order. mark in draw.go scales and fills them.",
           "var markFaces = []struct {",
           "\tcolor uint32",
           "\tpts   []f32.Point",
           "}{"]
    for col, pts in draw:
        points = ", ".join(f"{{X: {x:.1f}, Y: {y:.1f}}}" for x, y in pts)
        out.append(f"\t{{0x{col[1:]}, []f32.Point{{{points}}}}},")
    out += ["}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--slab", type=float, default=30)
    ap.add_argument("--gap", type=float, default=30)
    ap.add_argument("--svg")
    ap.add_argument("--plain")
    ap.add_argument("--go")
    args = ap.parse_args()
    # The desktop icon is drawn larger than the mark inside the window, so
    # the two are laid out separately rather than scaled from one set.
    draw = faces(args.slab, args.gap)
    if args.svg:
        icon = faces(args.slab, args.gap, ICON_MARK)
        open(args.svg, "w").write(svg(icon, args.slab, args.gap, plain=False))
        print("wrote", args.svg)
    if args.plain:
        open(args.plain, "w").write(svg(draw, args.slab, args.gap, plain=True))
        print("wrote", args.plain)
    if args.go:
        open(args.go, "w").write(go(draw))
        print("wrote", args.go)
    print(len(draw), "faces")
