"""Writes the Windows icon from the same model as the SVG and the OBJ.

Windows does not read an icon from a file next to the program the way a
desktop file does; it takes it from a resource compiled into the .exe. This
writes the .ico that the build embeds, at the sizes Windows asks for — the
list matters, because Windows picks the nearest size and scales it, and a
32 px icon scaled down to 16 turns the stack to mush.

Everything is drawn from iso_svg.faces(), so the icon in the taskbar is the
same artwork as the one in the dock and the mark inside the window. Nothing
here is imported beyond the standard library: the icon is regenerated by
hand now and then, and a build step that needs a wheel installed first is a
build step that stops working.

    python3 write_ico.py ../instant-launcher.ico
"""
import struct
import sys
import zlib

from iso_svg import ICON_MARK, TILE, faces

# Windows picks the nearest size and rescales, so the small ones are drawn
# rather than resampled. 256 is what Explorer's largest view and the task
# switcher use.
SIZES = (16, 24, 32, 48, 64, 128, 256)

# Supersampling for the edges. The marks are flat-shaded polygons that meet
# edge to edge, so coverage is all that has to be averaged — box-filtering a
# supersampled buffer is exactly right and keeps interior faces untouched.
SS = 4


def raster(polys, size):
    """Paint polygons back to front into `size` x `size` RGBA bytes."""
    n = size * SS
    grid = [[None] * n for _ in range(n)]

    for rgb, pts in polys:
        p = [(x * n / TILE, y * n / TILE) for x, y in pts]
        lo = max(0, int(min(y for _, y in p)))
        hi = min(n - 1, int(max(y for _, y in p)) + 1)
        for yy in range(lo, hi + 1):
            yc = yy + 0.5
            crossings = []
            for i in range(len(p)):
                x0, y0 = p[i]
                x1, y1 = p[(i + 1) % len(p)]
                if (y0 <= yc < y1) or (y1 <= yc < y0):
                    crossings.append(x0 + (yc - y0) * (x1 - x0) / (y1 - y0))
            crossings.sort()
            row = grid[yy]
            for i in range(0, len(crossings) - 1, 2):
                a = max(0, int(crossings[i] + 0.5))
                b = min(n - 1, int(crossings[i + 1] - 0.5))
                for xx in range(a, b + 1):
                    row[xx] = rgb

    out = bytearray(size * size * 4)
    full = SS * SS
    for y in range(size):
        rows = grid[y * SS:(y + 1) * SS]
        for x in range(size):
            r = g = b = hits = 0
            for row in rows:
                for c in row[x * SS:(x + 1) * SS]:
                    if c is not None:
                        r += c[0]
                        g += c[1]
                        b += c[2]
                        hits += 1
            if hits:
                i = (y * size + x) * 4
                out[i] = r // hits
                out[i + 1] = g // hits
                out[i + 2] = b // hits
                out[i + 3] = hits * 255 // full
    return bytes(out)


def png(rgba, size):
    """The smallest correct PNG: one IDAT of unfiltered RGBA rows."""
    raw = b"".join(b"\x00" + rgba[y * size * 4:(y + 1) * size * 4] for y in range(size))

    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw, 9))
            + chunk(b"IEND", b""))


def ico(images):
    """Pack (size, png bytes) into an .ico. 0 in the size byte means 256."""
    head = struct.pack("<HHH", 0, 1, len(images))
    offset = len(head) + 16 * len(images)
    entries, blobs = [], []
    for size, data in images:
        entries.append(struct.pack("<BBBBHHII", size % 256, size % 256, 0, 0,
                                   1, 32, len(data), offset))
        blobs.append(data)
        offset += len(data)
    return head + b"".join(entries) + b"".join(blobs)


def hexrgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "../instant-launcher.ico"
    polys = [(hexrgb(col), pts) for col, pts in faces(30, 30, ICON_MARK)]
    images = []
    for size in SIZES:
        images.append((size, png(raster(polys, size), size)))
        print("  drew", size)
    open(out, "wb").write(ico(images))
    print("wrote", out, len(ico(images)), "bytes,", len(SIZES), "sizes")
