// Code generated by packaging/mark/iso_svg.py; DO NOT EDIT.

package gui

import "gioui.org/f32"

// markFaces are the visible faces of the icon's model, projected into the
// 512-unit tile and lit like packaging/instant-launcher.svg, in drawing
// order. mark in draw.go scales and fills them.
var markFaces = []struct {
	color uint32
	pts   []f32.Point
}{
	{0x534540, []f32.Point{{X: 88.8, Y: 358.4}, {X: 256.0, Y: 442.0}, {X: 256.0, Y: 401.0}, {X: 88.8, Y: 317.4}}},
	{0x443A38, []f32.Point{{X: 256.0, Y: 442.0}, {X: 423.2, Y: 358.4}, {X: 423.2, Y: 317.4}, {X: 256.0, Y: 401.0}}},
	{0x5F4E46, []f32.Point{{X: 88.8, Y: 317.4}, {X: 256.0, Y: 401.0}, {X: 423.2, Y: 317.4}, {X: 256.0, Y: 233.8}}},
	{0x6F5545, []f32.Point{{X: 88.8, Y: 276.5}, {X: 256.0, Y: 360.1}, {X: 256.0, Y: 319.1}, {X: 88.8, Y: 235.5}}},
	{0x59453C, []f32.Point{{X: 256.0, Y: 360.1}, {X: 423.2, Y: 276.5}, {X: 423.2, Y: 235.5}, {X: 256.0, Y: 319.1}}},
	{0x7F604C, []f32.Point{{X: 88.8, Y: 235.5}, {X: 256.0, Y: 319.1}, {X: 423.2, Y: 235.5}, {X: 256.0, Y: 151.9}}},
	{0x91684D, []f32.Point{{X: 88.8, Y: 194.6}, {X: 256.0, Y: 278.2}, {X: 256.0, Y: 247.4}, {X: 88.8, Y: 163.8}}},
	{0x735441, []f32.Point{{X: 256.0, Y: 278.2}, {X: 423.2, Y: 194.6}, {X: 423.2, Y: 163.8}, {X: 256.0, Y: 247.4}}},
	{0xA67655, []f32.Point{{X: 88.8, Y: 163.8}, {X: 256.0, Y: 247.4}, {X: 423.2, Y: 163.8}, {X: 256.0, Y: 80.2}}},
	{0x6EA84E, []f32.Point{{X: 88.8, Y: 163.8}, {X: 256.0, Y: 247.4}, {X: 256.0, Y: 237.2}, {X: 88.8, Y: 153.6}}},
	{0x588642, []f32.Point{{X: 256.0, Y: 247.4}, {X: 423.2, Y: 163.8}, {X: 423.2, Y: 153.6}, {X: 256.0, Y: 237.2}}},
	{0x7DC057, []f32.Point{{X: 88.8, Y: 153.6}, {X: 256.0, Y: 237.2}, {X: 423.2, Y: 153.6}, {X: 256.0, Y: 70.0}}},
}
